
]
[2023-07-20 12:23:39,174: ERROR: main: >>>>> Stage | Data Ingestion Stage | Failed]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\components\data_ingestion.py", line 37, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-07-20 12:30:38,526: INFO: main: >>>>> Stage | Data Ingestion Stage | Started]
[2023-07-20 12:30:38,531: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 12:30:38,533: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 12:30:38,533: INFO: common: created directory at: artifacts]
[2023-07-20 12:30:38,534: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-20 12:30:39,041: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
Date: Thu, 20 Jul 2023 10:30:38 GMT
Cache-Control: no-cache, no-store
Pragma: no-cache
Set-Cookie: ka_sessionid=4521c2caaaad181557b710349f46bf1f; max-age=2626560; path=/
Set-Cookie: CSRF-TOKEN=CfDJ8MCGpmbK0d9IuUUyozUQ8_km1MQOxu3gdTwmEllA416OCPfQHC4ng00Z6PuLOi2Ih1hsZoxTWS8BULPCjEIJHIzOuWGZwxI0y03iDk2URw; path=/; secure; samesite=lax; httponly
Set-Cookie: XSRF-TOKEN=CfDJ8MCGpmbK0d9IuUUyozUQ8_nIKh7tiNOOSjamWZbB-LkUh323AJBYL2zmyl72tTXFJJTQmJFbDz45zFXMy-FvhbSq_cldTK4V-p-tpVYsYzXekQ; path=/; secure; samesite=lax
Set-Cookie: CLIENT-TOKEN=eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJrYWdnbGUiLCJhdWQiOiJjbGllbnQiLCJzdWIiOm51bGwsIm5idCI6IjIwMjMtMDctMjBUMTA6MzA6MzkuMDM3MzE5MloiLCJpYXQiOiIyMDIzLTA3LTIwVDEwOjMwOjM5LjAzNzMxOTJaIiwianRpIjoiMWZhZWZlZjAtZjllNy00NWUyLWFkYmUtZmE1YTgzODEyNzViIiwiZXhwIjoiMjAyMy0wOC0yMFQxMDozMDozOS4wMzczMTkyWiIsImFub24iOnRydWUsImZmIjpbIktlcm5lbHNGaXJlYmFzZUxvbmdQb2xsaW5nIiwiQ29tbXVuaXR5TG93ZXJIZWFkZXJTaXplcyIsIkFsbG93Rm9ydW1BdHRhY2htZW50cyIsIkZvcmNlTmF2Rm9vdGVyT25Nb2JpbGVBbmRUYWJsZXQiLCJGcm9udGVuZEVycm9yUmVwb3J0aW5nIiwiQ29tcGV0aXRpb25zUHl0aG9uTWV0cmljcyIsIkRhdGFzZXRzTWFuYWdlZEZvY3VzT25PcGVuIiwiRG9pRGF0YXNldFRvbWJzdG9uZXMiLCJDaGFuZ2VEYXRhc2V0T3duZXJzaGlwVG9PcmciLCJLZXJuZWxFZGl0b3JIYW5kbGVNb3VudE9uY2UiLCJLTUxvZ2dlZE91dEhvbWVwYWdlIiwiUGFnZVZpc2liaWxpdHlBbmFseXRpY3NSZXBvcnRlciIsIk1hdVJlcG9ydCIsIk1vZGVsc0NhY2hlZFRhZ1NlcnZpY2VFbmFibGVkIiwiQ29tcGV0aXRpb25zUnVsZXNLbSIsIkRhdGFzZXRzU2hhcmVkV2l0aFRoZW1TZWFyY2giLCJEYXRhc2V0c1ZvdGluZ0NoaXBzIiwiRGF0YXNldHNGZWVkYmFja3NCdXR0b25OdWRnZSIsIkRhdGFzZXRzRmVlZGJhY2tzRGVsYXlOdWRnZSIsIlRhZ3NNZW51U2xpZGVyUGFuZWwiLCJNb2RlbEluc3RhbmNlUmVuZGVyZWRVc2FnZSIsIlJlY2VudGx5Vmlld2VkTW9kZWxzU2hlbGYiLCJLbUVtb2ppUGlja2VyIiwiS01SYW5raW5ncyJdLCJmZmQiOnsiS2VybmVsRWRpdG9yQXV0b3NhdmVUaHJvdHRsZU1zIjoiMzAwMDAiLCJGcm9udGVuZEVycm9yUmVwb3J0aW5nU2FtcGxlUmF0ZSI6IjAiLCJFbWVyZ2VuY3lBbGVydEJhbm5lciI6Int9IiwiQ2xpZW50UnBjUmF0ZUxpbWl0IjoiNDAiLCJGZWF0dXJlZENvbW11bml0eUNvbXBldGl0aW9ucyI6IjM1MzI1LDM3MTc0LDMzNTc5LDM3ODk4LDM3MzU0LDM3OTU5LDM4ODYwIiwiQWRkRmVhdHVyZUZsYWdzVG9QYWdlTG9hZFRhZyI6ImRpc2FibGVkIiwiQ29tcGV0aXRpb25NZXRyaWNUaW1lb3V0TWludXRlcyI6IjMwIn0sInBpZCI6ImthZ2dsZS0xNjE2MDciLCJzdmMiOiJ3ZWItZmUiLCJzZGFrIjoiQUl6YVN5QTRlTnFVZFJSc2tKc0NaV1Z6LXFMNjU1WGE1SkVNcmVFIiwiYmxkIjoiOWQ1YjE4YjNhYTczOGFiYzg4N2NkMTFjNmEyNjM1NjVhYzM3MWY1ZSJ9.; path=/; secure; samesite=lax
Transfer-Encoding: chunked
Vary: Accept-Encoding
Turbolinks-Location: https://www.kaggle.com/account/login?titleType=dataset-downloads&showDatasetDownloadSkip=False&messageId=datasetsWelcome&returnUrl=%2Fdatasets%2Fnkifor%2Fpneumonia-dataset%2Fversions%2F1%3Fresource%3Ddownload
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Content-Security-Policy: object-src 'none'; script-src 'nonce-pp2iVzsXgNxF6HZ80/2XZA==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://form.jotform.com https://submit.jotform.us https://submit.jotformpro.com https://submit.jotform.com https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kkb-production.jupyter-proxy.kaggle.net https://kkb-production.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/;
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Via: 1.1 google
Set-Cookie: GCLB=CLaLhO_-zbOBfg; path=/; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close

]
[2023-07-20 12:30:39,053: ERROR: main: >>>>> Stage | Data Ingestion Stage | Failed]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\components\data_ingestion.py", line 37, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-07-20 16:33:33,931: INFO: main: >>>>> Stage | Data Ingestion Stage | Started]
[2023-07-20 16:33:33,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 16:33:33,946: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 16:33:33,947: INFO: common: created directory at: artifacts]
[2023-07-20 16:33:33,947: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-20 16:33:58,428: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
x-amz-id-2: wJfJffVFTlhG2w/SHto9Pr8ruXiY3vZsTU9PIx27kRG++vvqkyvYHzBv87AX6O9EMYB6blj0Y0A=
x-amz-request-id: KG3DSW4Q589TW81P
Date: Thu, 20 Jul 2023 14:33:35 GMT
Last-Modified: Thu, 20 Jul 2023 12:17:51 GMT
ETag: "1dd1f6e6ea0cae949a176df68fb56036-67"
x-amz-server-side-encryption: AES256
Accept-Ranges: bytes
Content-Type: application/zip
Server: AmazonS3
Content-Length: 1145020290
Connection: close

]
[2023-07-20 16:34:08,731: INFO: main: >>>>> Stage | Data Ingestion Stage | Finished 

 ========================================]
[2023-07-20 16:34:08,732: INFO: main: *******************]
[2023-07-20 16:34:08,732: INFO: main: >>>>>> Stage | Prepare base model | Started <<<<<<]
[2023-07-20 16:34:08,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 16:34:08,738: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 16:34:08,738: INFO: common: created directory at: artifacts]
[2023-07-20 16:34:08,739: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 16:34:09,240: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-07-20 16:34:09,431: INFO: main: >>>>>> Stage Prepare base model | Finished <<<<<<

x==========x]
[2023-07-20 16:34:09,432: INFO: main: *******************]
[2023-07-20 16:34:09,432: INFO: main: >>>>>> Stage | Training Stage | Started <<<<<<]
[2023-07-20 16:34:09,435: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 16:34:09,437: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 16:34:09,438: INFO: common: created directory at: artifacts]
[2023-07-20 16:34:09,439: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-20 16:34:09,440: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-20 16:34:09,442: INFO: common: created directory at: artifacts\training]
[2023-07-20 16:34:12,668: ERROR: main: >>>>> Stage | Training Stage | Failed]
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    model_trainer.main()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\components\training.py", line 71, in train
    self.model.fit(
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "main.py", line 37, in <module>
      model_trainer.main()
    File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\pipeline\stage_03_training.py", line 25, in main
      training.train(
    File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\components\training.py", line 71, in train
      self.model.fit(
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\training.py", line 1742, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\training.py", line 1338, in train_function
      return step_function(self, iterator)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\training.py", line 1322, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\training.py", line 1303, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\training.py", line 1081, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\training.py", line 1139, in compute_loss
      return self.compiled_loss(
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\losses.py", line 2122, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\keras\src\backend.py", line 5566, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,2] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1478]
[2023-07-20 17:16:39,693: INFO: main: >>>>> Stage | Data Ingestion Stage | Started]
[2023-07-20 17:16:39,696: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 17:16:39,698: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 17:16:39,699: INFO: common: created directory at: artifacts]
[2023-07-20 17:16:39,699: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-20 17:17:06,185: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
x-amz-id-2: xQVEM/bwt6J/49paeVo5U7M++vioWLAF1VlDQp22OTQDO2ihlzjl/HkyhrQfENPIv2aC/4vzolA=
x-amz-request-id: 95WS39FCNCBZDFZM
Date: Thu, 20 Jul 2023 15:16:41 GMT
Last-Modified: Thu, 20 Jul 2023 12:17:51 GMT
ETag: "1dd1f6e6ea0cae949a176df68fb56036-67"
x-amz-server-side-encryption: AES256
Accept-Ranges: bytes
Content-Type: application/zip
Server: AmazonS3
Content-Length: 1145020290
Connection: close

]
[2023-07-20 17:17:16,410: INFO: main: >>>>> Stage | Data Ingestion Stage | Finished 

 ========================================]
[2023-07-20 17:17:16,410: INFO: main: *******************]
[2023-07-20 17:17:16,410: INFO: main: >>>>>> Stage | Prepare base model | Started <<<<<<]
[2023-07-20 17:17:16,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 17:17:16,429: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 17:17:16,429: INFO: common: created directory at: artifacts]
[2023-07-20 17:17:16,430: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 17:17:16,784: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-07-20 17:17:16,973: INFO: main: >>>>>> Stage Prepare base model | Finished <<<<<<

x==========x]
[2023-07-20 17:17:16,973: INFO: main: *******************]
[2023-07-20 17:17:16,974: INFO: main: >>>>>> Stage | Training Stage | Started <<<<<<]
[2023-07-20 17:17:16,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 17:17:16,979: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 17:17:16,979: INFO: common: created directory at: artifacts]
[2023-07-20 17:17:16,980: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-20 17:17:16,981: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-20 17:17:16,983: INFO: common: created directory at: artifacts\training]
[2023-07-20 17:37:05,731: INFO: main: >>>>>> Stage | Training Stage | Finished <<<<<<

x==========x]
[2023-07-20 17:37:05,731: INFO: main: *******************]
[2023-07-20 17:37:05,731: INFO: main: >>>>>> Stage | Evaluation stage | Started <<<<<<]
[2023-07-20 17:37:05,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 17:37:05,743: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 17:37:05,743: INFO: common: created directory at: artifacts]
[2023-07-20 17:38:12,045: INFO: common: json file saved at: scores.json]
[2023-07-20 17:38:12,045: INFO: main: >>>>>> Stage Evaluation stage Completed <<<<<<

x==========x]
[2023-07-21 10:59:00,014: INFO: stage_01_data_ingestion: >>>>> Stage | Data Ingestion Stage | Started]
[2023-07-21 10:59:00,017: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 10:59:00,019: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 10:59:00,020: INFO: common: created directory at: artifacts]
[2023-07-21 10:59:00,022: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-21 10:59:00,022: INFO: data_ingestion: File already exists of size: ~ 1118184 KB]
[2023-07-21 10:59:10,832: INFO: stage_01_data_ingestion: >>>>> Stage | Data Ingestion Stage | Finished 

 ========================================]
[2023-07-21 11:00:05,233: INFO: stage_02_prepare_base_model: *******************]
[2023-07-21 11:00:05,234: INFO: stage_02_prepare_base_model: >>>>>> Stage | Prepare Base Model Stage | Started <<<<<<]
[2023-07-21 11:00:05,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 11:00:05,240: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 11:00:05,240: INFO: common: created directory at: artifacts]
[2023-07-21 11:00:05,241: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-21 11:00:05,690: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-07-21 11:00:05,867: INFO: stage_02_prepare_base_model: >>>>>> Stage | Prepare Base Model Stage | Finished <<<<<<

x==========x]
[2023-07-21 11:00:14,122: INFO: stage_03_training: *******************]
[2023-07-21 11:00:14,123: INFO: stage_03_training: >>>>>> Stage | Training Stage | Started <<<<<<]
[2023-07-21 11:00:14,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 11:00:14,128: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 11:00:14,128: INFO: common: created directory at: artifacts]
[2023-07-21 11:00:14,129: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-21 11:00:14,129: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-21 11:00:14,131: INFO: common: created directory at: artifacts\training]
[2023-07-21 11:27:08,700: INFO: stage_03_training: >>>>>> Stage | Training Stage | Finished <<<<<<

x==========x]
[2023-07-21 11:27:19,455: INFO: stage_04_evaluation: *******************]
[2023-07-21 11:27:19,455: INFO: stage_04_evaluation: >>>>>> Stage | Evaluation stage | Started <<<<<<]
[2023-07-21 11:27:19,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 11:27:19,470: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 11:27:19,471: INFO: common: created directory at: artifacts]
[2023-07-21 11:28:21,424: INFO: common: json file saved at: scores.json]
[2023-07-21 11:28:21,425: INFO: stage_04_evaluation: >>>>>> Stage | Evaluation stage | Finished <<<<<<

x==========x]
[2023-07-21 11:51:25,155: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 11:51:25,156: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 11:51:46,988: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 11:51:46] "GET / HTTP/1.1" 200 -]
[2023-07-21 11:52:12,755: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\pipeline\predict.py", line 27, in predict
    if result[1] == 1:
IndexError: index 1 is out of bounds for axis 0 with size 1
[2023-07-21 11:52:12,761: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 11:52:12] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-21 12:15:54,007: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 12:15:54,008: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 12:15:59,300: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:15:59] "GET / HTTP/1.1" 200 -]
[2023-07-21 12:16:04,381: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:16:04] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:16:14,914: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:16:14] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:16:22,222: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:16:22] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:16:26,751: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:16:26] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:16:31,258: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000014A1B029E50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-21 12:16:31,264: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:16:31] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:16:38,378: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000014A1B180790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-21 12:16:38,384: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Admin\anaconda3\envs\mlops\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
  File "c:\edu\python\mlops_projects\mlops_pneumonia_xray_detector\src\CNN_pneumonia_xray_detector\pipeline\predict.py", line 27, in predict
    if result[1] == 1:
IndexError: index 1 is out of bounds for axis 0 with size 1
[2023-07-21 12:16:38,388: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:16:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-21 12:18:08,948: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 12:18:08,949: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 12:18:13,342: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:13] "GET / HTTP/1.1" 200 -]
[2023-07-21 12:18:18,123: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:18] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:18:23,894: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:23] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:18:30,558: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:30] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:18:36,403: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:36] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:18:44,474: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000181824219D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-21 12:18:44,481: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:44] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:18:52,407: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000181824218B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-21 12:18:52,414: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:52] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:18:59,164: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:18:59] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:09,188: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:09] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:14,415: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:14] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:21,680: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:21] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:26,490: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:26] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:32,451: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:32] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:37,639: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:37] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:19:44,216: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:19:44] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:23:05,503: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 12:23:05,504: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 12:23:11,832: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:23:11] "GET / HTTP/1.1" 200 -]
[2023-07-21 12:23:17,910: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:23:17] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:23:43,455: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:23:43] "GET / HTTP/1.1" 200 -]
[2023-07-21 12:26:43,788: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 12:26:43,789: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 12:26:49,253: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:26:49] "GET / HTTP/1.1" 200 -]
[2023-07-21 12:27:49,787: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 12:27:49,788: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 12:27:53,978: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:27:53] "GET / HTTP/1.1" 200 -]
[2023-07-21 12:28:35,610: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:28:35] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:28:43,124: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:28:43] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:28:48,195: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 12:28:48] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 12:36:05,206: INFO: stage_03_training: *******************]
[2023-07-21 12:36:05,206: INFO: stage_03_training: >>>>>> Stage | Training Stage | Started <<<<<<]
[2023-07-21 12:36:05,214: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 12:36:05,216: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 12:36:05,217: INFO: common: created directory at: artifacts]
[2023-07-21 12:36:05,217: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-21 12:36:05,218: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-21 12:36:05,220: INFO: common: created directory at: artifacts\training]
[2023-07-21 13:19:54,340: INFO: stage_03_training: >>>>>> Stage | Training Stage | Finished <<<<<<

x==========x]
[2023-07-21 13:20:06,758: INFO: stage_04_evaluation: *******************]
[2023-07-21 13:20:06,758: INFO: stage_04_evaluation: >>>>>> Stage | Evaluation stage | Started <<<<<<]
[2023-07-21 13:20:06,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 13:20:06,776: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 13:20:06,777: INFO: common: created directory at: artifacts]
[2023-07-21 13:21:12,818: INFO: common: json file saved at: scores.json]
[2023-07-21 13:21:12,819: INFO: stage_04_evaluation: >>>>>> Stage | Evaluation stage | Finished <<<<<<

x==========x]
[2023-07-21 13:22:07,058: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 13:22:07,059: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 13:45:55,310: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.248:8080]
[2023-07-21 13:45:55,311: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-21 13:45:59,576: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:45:59] "GET / HTTP/1.1" 200 -]
[2023-07-21 13:46:12,195: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:12] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 13:46:24,838: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:24] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 13:46:30,014: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:30] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 13:46:35,501: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:35] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 13:46:40,047: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000019510B319D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-21 13:46:40,054: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:40] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 13:46:44,781: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000019510B318B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-21 13:46:44,787: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:44] "POST /predict HTTP/1.1" 200 -]
[2023-07-21 13:46:56,837: INFO: _internal: 192.168.0.248 - - [21/Jul/2023 13:46:56] "POST /predict HTTP/1.1" 200 -]
